### PR TITLE
Allow FullCameraViewer to be zoomable (Pinch to zoom)

### PR DESCRIPTION
**Pull request by Scrumplex**
# Summary
This PR adds the functionality to be able to zoom in or out on the FullCameraViewer.

# Dependencies
- This PR adds [TouchImageViewer](https://github.com/MikeOrtiz/TouchImageView) as a dependency
   - As we are using Android Support instead of Android X we are using the last version supporting Android Support.

# How it looks
See it on PeerTube: https://bittube.video/videos/watch/510d0228-b8ca-4426-b89b-6498a85d5a07

### CODE REVIEW

**Comment by Scrumplex** [comment]
Looks like my recording software messed up the last half of the preview video. Was meant to be landscape, but got squished for some reason

**Comment by developerfromjokela** [comment]
Are actions working? When you click the image frame, it should reveal actions.

**Comment by Scrumplex** [comment]
Screenshot

Now they were moved to the edges of the screen, as the container is not as large as the screen. In my opinion this looks better, though, as it now does not cover anything of the image

**Comment by developerfromjokela** [comment]
Ok. I'll test it on my device, and I'll merge if it works fine. :smile:

**Comment by developerfromjokela** [comment]
Got a little problem here. Actions are working great, but the navigation actions aren't showing up. 

Screenshot_1580141423

Screenshot_1580141492

**Comment by developerfromjokela** [comment]
I've moved them to the bottom bar like this:
Do you have you better ideas, or mine is great enough?

Screenshot_1580141795

**Review by developerfromjokela — COMMENTED** [review]
Great improvement, I'll add the navigation actions into the bottom bar, and we're good.

**Comment by developerfromjokela** [comment]
@Scrumplex Is that design ok?

**Comment by Scrumplex** [comment]
Oh sorry. I forgot to respond. Yes your design looks good to me

**Comment by developerfromjokela** [comment]
I'll run final tests, if everything works with no issues, I'll merge this PR

**Comment by developerfromjokela** [comment]
It works fine

**Comment by Scrumplex** [comment]
:tada:

**Pull request merged**
